### ISSUE TITLE
Primary button in HighContrast mode doesn't match design

### ISSUE THREAD

**Issue by ValentinaKozlova** [microsoft/fluentui-react-native#1092]
- **Platform**:
  - [ ] iOS
    - **Xcode version**:
  - [ ] macOS
    - **Xcode version**:
  - [X] win32
  - [ ] windows
  - [ ] android

### Please provide a reproduction of the bug:
1. Switch computer to HighContrast mode
2. Open ExperimentalButton in Tester.
3. Switch the theme to Office.

#### Actual behavior:
Primary button doesn't match the design:
![image](https://user-images.githubusercontent.com/11574680/138508869-7939933f-3c70-46ce-96bc-6dfdfa3c5c81.png)

Button on hover has white font color:
![image](https://user-images.githubusercontent.com/11574680/138508927-13458a75-9c7a-40ad-a100-e4059a19af56.png)

#### Expected behavior:
Primary button default:
![image](https://user-images.githubusercontent.com/11574680/138509222-265b1879-fb03-4cfc-aa07-0e4d477e07e5.png)

Primary button hover:
![image](https://user-images.githubusercontent.com/11574680/138509289-c23ef37e-d738-4d5e-9131-e16b24a58305.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low)

Products/applications affected: (if applicable)

**Comment by rurikoaraki** [comment]
@ValentinaKozlova This is a miss on my part for not having documented this but when you tested High Contrast, did you start the app while the computer was in high contrast mode, and switch the theme to Office? The colors we use in HC pull from the system brushes and the palette, which is influenced by the system being in HC, and the app starting in HC so that we pull the right palette entries. Also, we don't have the correct palette if you run with the web debugger due to technical issues, unfortunately, so when testing colors we should make sure to run the release bundle.

I do see HC bugs on hover, so that's something to note and fix:
![image](https://user-images.githubusercontent.com/4602628/138342545-5b706159-07bd-4d8b-84ba-185f7904fde8.png)
