### ISSUE TITLE
useCompoundPrepare always calls createSlotRenderInfo

### ISSUE THREAD

**Issue by konvolution** [microsoft/fluentui-react-native#363]
This is the code I'm referring to:

https://github.com/microsoft/fluentui-react-native/blob/7fbc40950203a0235240f455752b5a5fcc582801/packages/framework/foundation-composable/src/Composable.slots.ts#L116

I think the intention is to only call createSlotRenderInfo() once. However, that's not the case. Unless I'm mistaken, you probably want to do

   const renderInfo = useMemo(() => createSlotRenderInfo(...), []);

or, equivalently;

  const [renderInfo] = useState(() => createSlotRenderInfo(...));

**Comment by JasonVMo** [comment]
Good catch! There are two parts to this call but as it is written now (I think) it only does half of it and the suggested change will fix it. 

The first part is to ensure that the closures for the slots aren't recreated on every render because react will treat this as a different component on every pass.  I think that is working correctly because the value is stored only once.

Unfortunately as written the fairly expensive createSlotRenderInfo routine is running on every render.
