### ISSUE TITLE
Hook up react-test-app for android

### ISSUE THREAD

**Issue by JasonVMo** [microsoft/fluentui-react-native#427]
#### Platform
- [ ] iOS
- [ ] macOS
- [ ] win32
- [ ] windows
- [x] android
 
#### Describe the feature that you would like added

Right now it is too hard to test android versions of the components. To achieve this the test app from the Oslo team needs to be integrated into the repo.

#### What component or utility would this be added to

Likely apps/android would be the location for it in the repo.

**Comment by tido64** [comment]
cc @arazabishov @Saadnajmi

**Comment by tido64** [comment]
@JasonVMo I opened an issue here: #239. Should we close that one since most of the tasks are done?

**Comment by Saadnajmi** [comment]
Right, I have a branch on my personal fork attempting this and ran into a null pointer exception on boot, which I asked @arazabishov to investigate.

**Comment by arazabishov** [comment]
@Saadnajmi sorry for being slow, got swamped by other work. I'm looking at this now.

**Comment by Saadnajmi** [comment]
> @JasonVMo: Our Windows (UWP) test app just landed. Should we create a new issue for it?
> 
> @Saadnajmi: Last week, I heard that the crash was due to mismatched Hermes version and that it got resolved after a rebase. Does this mean we can move forward now? What's the latest on this?

Still ran into another crash after updating hermes on Android, unfortunately

**Comment by tido64** [comment]
> @Saadnajmi: Still ran into another crash after updating hermes on Android, unfortunately

I checked out [your branch](https://github.com/Saadnajmi/fluentui-react-native/tree/android), and it seemed to boot up fine after the second try for me. It crashed the first time around because I didn't have the dev server running. The test app was supposed to show a RedBox but there's a bug on our side that dismisses it right away: https://github.com/microsoft/react-native-test-app/pull/214. This should be fixed in 0.2.1:

| | |
|-|-|
| ![image](https://user-images.githubusercontent.com/4123478/92483724-73299380-f1e9-11ea-8b2a-e7c2bffa7fe8.png) | ![image](https://user-images.githubusercontent.com/4123478/92485364-22b33580-f1eb-11ea-907f-20755cd6faa5.png) |

**Comment by Saadnajmi** [comment]
Thanks @tido64 for the update! I'll check out the latest version locally in my branch and if all checks out send a PR!
