### ISSUE TITLE
Use a Standard "size" enum for components

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/fluentui-react-native#475]
#### Platform
- [x] iOS
- [x] macOS
- [x] win32
- [x] windows
- [x] android
 
#### Describe the feature that you would like added

Some components like Spinner and PersonaCoin specify different sizes that their control can exist as. They either use strings like "small", "medium", xLarge", or numbers like "size24", "size48"

Let's perhaps just standardize to one size enum since design likes to change the point sizes frequently?

```
export type Size = 'xSmall' | 'small' | 'medium' | 'large' | 'xLarge' | 'xxLarge';
```
#### What component or utility would this be added to

Spinner, PersonaCoin

#### Have you discussed this feature with our team, and if so, who

Yes, @JasonVMo and @harrieshin  

#### Additional context/screenshots

https://github.com/microsoft/fluentui-react-native/pull/462#discussion_r492182757

**Comment by tkamireh** [comment]
Part of the problem here is that the naming is generally meant to align with design. I agree that it is annoying, but I believe part of the thinking is that we'd rather be aligned with where the fluent design language is than across components at this point (which is debatable, I actually tend to agree with you).

AB#4903346

**Comment by rurikoaraki** [comment]
This should get standardized as we move to v1. Primarily driven by design.
